package com.course.model;

/**
 * Description ApiAutoTest
 * Create by qym on 2020/1/9 11:20
 * @author qym
 */

public enum InterfaceName {
    LOGIN,GETTICKET,ADDORUPDATE,FINDORG,ADDORGNAME,DELETEORG,FINDORGNAME,ADDORGPRODUCTAUTH,FINDORGPRODUCTAUTH,
    ADDROLEORUPDATE,FINDROLELIST,ADDROLEMENU,ADDGRAYSETTING,FINDGRAYORG,
    ADDUSER,FINDUSER,INITPASSWORD,ADDMENUUPDATE,FINDMENU,DELETEMENU,ADDFILEINFO,
    SELECTORGANIZATIONTREE,FINDLOG,DELETEROLE,DELETEGRAYORG,DELETEORGPRODUCTAUTH
}