server:
  port: 8989

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasourse:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.110:3306/course?serverTimezone=UTC
    username: root
    password: 123456


mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*