package com.course.model;

/**
 * 将需要测试的接口进行枚举，防止使用 测试范围外的非法接口
 */
public enum InterfaceName {
    LOGIN,ADDPRODUCT,UPDATEPRODUCT,GETTICKET,LOOKPRODUCT,LOOKWHITEPRODUCTLIST,LOOKWHITELIST,LOOKWHITEENTERPRISELIST,IMPORTWHITELIST,DOWNLOADTEMPLATE,PRODUCTSHELVES,LOGINOUT,H5LOGIN,FIND
}